### ISSUE TITLE
onboarding for @pkarman

### ISSUE THREAD

**Issue by afeld** [18F/C2#565]
## Tasks for @pkarman

* [x] [Set up your development environment](https://github.com/18F/C2/blob/master/doc/setup.md)
* [x] Go through the rest of the [general documentation](https://github.com/18F/C2#general)

### Later

* [x] [Set up the Cloud Foundry CLI](https://docs.18f.gov/getting-started/setup/) (which you will need to deploy)
* [x] [Learn more about Cloud Foundry](https://docs.18f.gov)
* [x] Deploy C2 to `c2-dev` (or `c2-staging`)

## Tasks for @afeld

* [x] Add to Slack channels
* [x] [Add to Pivotal Tracker](https://www.pivotaltracker.com/projects/1149728/memberships)
* [x] Add to [@18F/cap](https://github.com/orgs/18F/teams/cap) team on GitHub
* [x] Add to calendar items: standups, IPM, and story grooming sessions
* [x] Schedule a code walkthrough
* [x] Set up pairing session
* [x] Give intro to [current stories](https://pivotaltracker.com/n/projects/1149728)
* [x] Give intro to weekly ceremonies and team workflow

### Later

* [x] [Add them to `cap` organization on Cloud Foundry](https://docs.cloudfoundry.org/adminguide/cli-user-management.html#org-roles) (`cf set-org-role USERNAME cap OrgManager`)
* [ ] Admin access to C2 production (add to `ADMIN_EMAILS`)

**Comment by pkarman** [comment]
I think I've done everything, and just created #584 to reflect changes to this for the next person.
