### ISSUE TITLE
Onboarding for @jessieay

### ISSUE THREAD

**Issue by afeld** [18F/C2#662]
## Tasks for @jessieay 

* [x] [Set up your development environment](https://github.com/18F/C2/blob/master/doc/setup.md)
* [x] Go through the rest of the [general documentation](https://github.com/18F/C2#general)
* [x] Subscribe to the project on CircleCI
    1. [Authorize With GitHub](https://circleci.com/signup)
    1. Go to [the project page](https://circleci.com/gh/18F/C2) and "follow the C2 project"

### Later

* [x] [Set up the Cloud Foundry CLI](https://docs.18f.gov/getting-started/setup/) (which you will need to deploy)
* [x] [Learn more about Cloud Foundry](https://docs.18f.gov)
* [ ] Deploy C2 to `c2-dev` (or `c2-staging`)
* [ ] [Get added to the MailChimp account](production.md#getting-access)
* [ ] Access support emails `capdevs@gsa.gov`, `communicart.sender@gsa.gov`, and `gatewaycommunicator`
    1. Make sure someone has requested/completed access for you (See tasks below)
    1. Go to Gmail and click 'Add Account'. Enter in each of these email addresses. If you are asked for a password, leave it blank. As long as you are already logged into your GSA email, the email addresses should be loaded.
    1. One would expect the newly added email to load automatically, but it doesn't. To load the new email, simply click on your email address at the top right of the page to show all of your loaded email accounts. Click on the newly added email address (capdevs or communicart.sender) to load it.

## Tasks for @afeld

* [x] Add to Slack channels
* [x] [Add to Pivotal Tracker](https://www.pivotaltracker.com/projects/1149728/memberships)
* [x] Add to [@18F/cap](https://github.com/orgs/18F/teams/cap) team on GitHub
* [ ] Add to support emails: `capdevs`, `communicart.sender`, and `gatewaycommunicator` through [IT Service Desk](https://gsa.service-now.com)
* [x] Add to calendar items: standups, IPM, and story grooming sessions
* [ ] Schedule a code walkthrough
* [ ] Set up pairing session
* [ ] Give intro to [current stories](https://pivotaltracker.com/n/projects/1149728)
* [ ] Give intro to weekly ceremonies and team workflow

### Later

* [ ] [Add them to `cap` organization on Cloud Foundry](https://docs.cloudfoundry.org/adminguide/cli-user-management.html#org-roles) (`cf set-org-role USERNAME cap OrgManager`)
* [ ] Admin access to C2 production (add UserRole `admin` to User record)

**Comment by jessieay** [comment]
@afeld should I file an IT service desk request for access to the support emails, or is that for someone else to do? If it is a task for me, would love more info on how to submit the request because I just tried and it was confusing

**Comment by afeld** [comment]
@phirefly: You've done it in the past...mind adding instructions?

**Comment by jessieay** [comment]
Hey @afeld can you add me to mailchimp please? My username is jessieyoung18f

**Comment by afeld** [comment]
Looks like you already had access...no?

**Comment by jessieay** [comment]
I have mailchimp access to some orgs, but nothing that looks C2-ish

these are the orgs I have access to in mailchimp:
![screen shot 2015-11-06 at 9 54 40 am 1](https://cloud.githubusercontent.com/assets/601515/11004441/20b38fdc-846d-11e5-86fd-1e05370fd8cd.png)

also not seeing any data when I am logged into mandrill...

**Comment by afeld** [comment]
Got the Mailchimp thing sorted over screenshare.

Closing this as you're fairly fully onboarded, though feel free to continue commenting here if you need anything!
