### ISSUE TITLE
onboarding for Leonard

### ISSUE THREAD

**Issue by pkarman** [18F/C2#930]
# Onboarding for @rememberlenny 

## Tasks for @rememberlenny

* [x] [Set up your development environment](https://github.com/18F/C2/blob/master/doc/setup.md)
* [x] Go through the rest of the [general documentation](https://github.com/18F/C2#general)
* [x] Subscribe to the project on CircleCI
    1. [Authorize With GitHub](https://circleci.com/signup)
    1. Go to [the project page](https://circleci.com/gh/18F/C2) and "follow the C2 project"

### Later

* [x] [Set up the Cloud Foundry CLI](https://docs.cloud.gov/getting-started/setup/) (which you will need to deploy)
* [x] [Learn more about Cloud Foundry](https://docs.cloud.gov)
* [x] Deploy C2 to `c2-dev` (or `c2-staging`)
* [x] [Get added to the MailChimp account](production.md#getting-access) (and thus Mandrill)
* [x] Access support emails `capdevs@gsa.gov`, `communicart.sender@gsa.gov`, and `gatewaycommunicator`
    1. Make sure someone has requested/completed access for you (See tasks for @phirefly)
    1. Go to Gmail and click 'Add Account'. Enter in each of these email addresses. If you are asked for a password, leave it blank. As long as you are already logged into your GSA email, the email addresses should be loaded.
    1. One would expect the newly added email to load automatically, but it doesn't. To load the new email, simply click on your email address at the top right of the page to show all of your loaded email accounts. Click on the newly added email address (capdevs or communicart.sender) to load it.

## Tasks for @phirefly 

* [x] Add to Slack channels
* [x] [Add to the kanban board](https://trello.com/b/kAW72R3m/c2-birthday-cake)
* [x] [Add to Trello](https://trello.com/b/kAW72R3m/c2-birthday-cake)
* [x] Add to [@18F/cap](https://github.com/orgs/18F/teams/cap) team on GitHub
* [x] Add to support emails: `capdevs`, `communicart.sender`, and `gatewaycommunicator` through [IT Service Desk](https://gsa.service-now.com)
* [x] Send access information for developer test emails: `gsa.approver`, `communicart.budget.approver`, and `communicart.ofm.approver`)
* [x] [Add to New Relic](https://rpm.newrelic.com/accounts/921394)
* [x] Add to calendar items: standups, IPM, and story grooming sessions
* [x] Schedule a code walkthrough
* [x] Set up pairing session
* [x] Give intro to [current stories](https://trello.com/b/kAW72R3m/c2-birthday-cake)
* [x] Give intro to weekly ceremonies and team workflow

### Later

* [x] [Add them to `cap` organization on Cloud Foundry](https://docs.cloudfoundry.org/adminguide/cli-user-management.html#org-roles) (`cf set-org-role USERNAME cap OrgManager`)
* [x] [Add them to the repository on Hakiri.](https://hakiri.io/projects/ed076f492b8f5a/edit)
* [x] Admin access to C2 production (add UserRole `admin` to User record)
* [x] Access [application logs](https://logs.cloud.gov/app/kibana)
* [x] Access to [User Voice](https://www.uservoice.com/)
* [x] Access to [Stories on Board](https://www.storiesonboard.com/)
* [x] Link to Google Drive files
